using System.Data;
using Dapper;
using Domain.Models.Requests;
using Domain.Models.Responses;
using Domain.Services.Interfaces;
using Helpers.Common;
using Infrastructure.Data;
using Infrastructure.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;

namespace Domain.Services.Implementations
{
    public class ItemService(
        IItemRepository itemRepository, 
        IItemVariantRepository itemVariantRepository,
        IItemAttributeRepository itemAttributeRepository,
        IItemVariantAttributeRepository itemVariantAttributeRepository,
        string connectionString) : IItemService
    {
        private readonly IItemRepository _itemRepository = itemRepository;
        private readonly IItemVariantRepository _itemVariantRepository = itemVariantRepository;
        private readonly IItemAttributeRepository _itemAttributeRepository = itemAttributeRepository;
        private readonly IItemVariantAttributeRepository _itemVariantAttributeRepository = itemVariantAttributeRepository;
        private readonly string _connectionString = connectionString;

        public async Task<Result<CreateItemResponse>> CreateItemAsync(CreateItemRequest createItemRequest)
        {
            try
            {
                var validationResult = createItemRequest.Validate();
                if (validationResult.IsFailure)
                {
                    return Result.Failure<CreateItemResponse>(validationResult.Error!, validationResult.ErrorCode ?? 400);
                }

                var createdAt = DateTime.UtcNow;

                // Prepare Item (Id will be generated by database)
                var item = new Item
                {
                    SellerID = createItemRequest.SellerID,
                    Name_en = createItemRequest.Name_en,
                    Name_fr = createItemRequest.Name_fr,
                    Description_en = createItemRequest.Description_en,
                    Description_fr = createItemRequest.Description_fr,
                    CategoryID = createItemRequest.CategoryID,
                    CreatedAt = createdAt,
                    UpdatedAt = null,
                    Deleted = false
                };

                // Prepare ItemAttributes (Id and ItemID will be set after Item is inserted)
                var itemAttributeRequests = createItemRequest.ItemAttributes.ToList();

                // Prepare ItemVariants and ItemVariantAttributes (Ids will be set after insertion)
                var itemVariantRequests = createItemRequest.Variants.ToList();

                // Execute all database operations in a single transaction
                using var connection = new SqlConnection(_connectionString);
                await connection.OpenAsync();
                using var transaction = connection.BeginTransaction();

                try
                {
                    // 1. Insert Item and get database-generated Id
                    try
                    {
                        var itemQuery = @"
INSERT INTO dbo.Item (
    SellerID,
    Name_en, 
    Name_fr, 
    Description_en, 
    Description_fr, 
    CategoryID, 
    CreatedAt, 
    UpdatedAt, 
    Deleted)
OUTPUT INSERTED.Id
VALUES (
    @SellerID,
    @Name_en, 
    @Name_fr, 
    @Description_en, 
    @Description_fr, 
    @CategoryID, 
    @CreatedAt, 
    @UpdatedAt, 
    @Deleted)";

                        var itemId = await connection.ExecuteScalarAsync<Guid>(itemQuery, item, transaction);
                        item.Id = itemId;
                    }
                    catch (SqlException sqlEx)
                    {
                        throw new InvalidOperationException($"Database error inserting Item: {sqlEx.Message}", sqlEx);
                    }
                    catch (Exception ex)
                    {
                        throw new InvalidOperationException($"Failed to insert Item: {ex.Message}", ex);
                    }

                    // 2. Insert ItemAttributes
                    var itemAttributes = new List<ItemAttribute>();
                    if (itemAttributeRequests.Any())
                    {
                        try
                        {
                            var itemAttributeQuery = @"
INSERT INTO dbo.ItemAttribute (ItemID, AttributeName_en, AttributeName_fr, Attributes_en, Attributes_fr)
OUTPUT INSERTED.Id
VALUES (@ItemID, @AttributeName_en, @AttributeName_fr, @Attributes_en, @Attributes_fr)";

                            foreach (var attributeRequest in itemAttributeRequests)
                            {
                                var attributeId = await connection.ExecuteScalarAsync<Guid>(itemAttributeQuery, new
                                {
                                    ItemID = item.Id,
                                    attributeRequest.AttributeName_en,
                                    attributeRequest.AttributeName_fr,
                                    attributeRequest.Attributes_en,
                                    attributeRequest.Attributes_fr
                                }, transaction);

                                itemAttributes.Add(new ItemAttribute
                                {
                                    Id = attributeId,
                                    ItemID = item.Id,
                                    AttributeName_en = attributeRequest.AttributeName_en,
                                    AttributeName_fr = attributeRequest.AttributeName_fr,
                                    Attributes_en = attributeRequest.Attributes_en,
                                    Attributes_fr = attributeRequest.Attributes_fr
                                });
                            }
                        }
                        catch (SqlException sqlEx)
                        {
                            throw new InvalidOperationException($"Database error inserting ItemAttributes: {sqlEx.Message}", sqlEx);
                        }
                        catch (Exception ex)
                        {
                            throw new InvalidOperationException($"Failed to insert ItemAttributes: {ex.Message}", ex);
                        }
                    }

                    // 3. Insert ItemVariants
                    var itemVariants = new List<ItemVariant>();
                    var itemVariantAttributes = new List<ItemVariantAttribute>();
                    if (itemVariantRequests.Any())
                    {
                        try
                        {
                            var itemVariantQuery = @"
INSERT INTO dbo.ItemVariant (
    ItemId,
    Price,
    StockQuantity,
    Sku,
    ProductIdentifierType,
    ProductIdentifierValue,
    ImageUrls,
    ThumbnailUrl,
    ItemVariantName_en,
    ItemVariantName_fr,
    Deleted,
    Offer,
    OfferStart,
    OfferEnd)
OUTPUT INSERTED.Id
VALUES (
    @ItemId,
    @Price,
    @StockQuantity,
    @Sku,
    @ProductIdentifierType,
    @ProductIdentifierValue,
    @ImageUrls,
    @ThumbnailUrl,
    @ItemVariantName_en,
    @ItemVariantName_fr,
    @Deleted,
    @Offer,
    @OfferStart,
    @OfferEnd)";

                            foreach (var variantRequest in itemVariantRequests)
                            {
                                var variantId = await connection.ExecuteScalarAsync<Guid>(itemVariantQuery, new
                                {
                                    ItemId = item.Id,
                                    variantRequest.Price,
                                    variantRequest.StockQuantity,
                                    variantRequest.Sku,
                                    variantRequest.ProductIdentifierType,
                                    variantRequest.ProductIdentifierValue,
                                    variantRequest.ImageUrls,
                                    variantRequest.ThumbnailUrl,
                                    variantRequest.ItemVariantName_en,
                                    variantRequest.ItemVariantName_fr,
                                    variantRequest.Deleted,
                                    variantRequest.Offer,
                                    variantRequest.OfferStart,
                                    variantRequest.OfferEnd
                                }, transaction);

                                var variant = new ItemVariant
                                {
                                    Id = variantId,
                                    ItemId = item.Id,
                                    Price = variantRequest.Price,
                                    StockQuantity = variantRequest.StockQuantity,
                                    Sku = variantRequest.Sku,
                                    ProductIdentifierType = variantRequest.ProductIdentifierType,
                                    ProductIdentifierValue = variantRequest.ProductIdentifierValue,
                                    ImageUrls = variantRequest.ImageUrls,
                                    ThumbnailUrl = variantRequest.ThumbnailUrl,
                                    ItemVariantName_en = variantRequest.ItemVariantName_en,
                                    ItemVariantName_fr = variantRequest.ItemVariantName_fr,
                                    Deleted = variantRequest.Deleted,
                                    Offer = variantRequest.Offer,
                                    OfferStart = variantRequest.OfferStart,
                                    OfferEnd = variantRequest.OfferEnd
                                };
                                itemVariants.Add(variant);

                                // 4. Insert ItemVariantAttributes for this variant
                                if (variantRequest.ItemVariantAttributes.Any())
                                {
                                    try
                                    {
                                        var itemVariantAttributeQuery = @"
INSERT INTO dbo.ItemVariantAttribute (ItemVariantID, AttributeName_en, AttributeName_fr, Attributes_en, Attributes_fr)
OUTPUT INSERTED.Id
VALUES (@ItemVariantID, @AttributeName_en, @AttributeName_fr, @Attributes_en, @Attributes_fr)";

                                        foreach (var variantAttributeRequest in variantRequest.ItemVariantAttributes)
                                        {
                                            var variantAttributeId = await connection.ExecuteScalarAsync<Guid>(itemVariantAttributeQuery, new
                                            {
                                                ItemVariantID = variantId,
                                                variantAttributeRequest.AttributeName_en,
                                                variantAttributeRequest.AttributeName_fr,
                                                variantAttributeRequest.Attributes_en,
                                                variantAttributeRequest.Attributes_fr
                                            }, transaction);

                                            itemVariantAttributes.Add(new ItemVariantAttribute
                                            {
                                                Id = variantAttributeId,
                                                ItemVariantID = variantId,
                                                AttributeName_en = variantAttributeRequest.AttributeName_en,
                                                AttributeName_fr = variantAttributeRequest.AttributeName_fr,
                                                Attributes_en = variantAttributeRequest.Attributes_en,
                                                Attributes_fr = variantAttributeRequest.Attributes_fr
                                            });
                                        }
                                    }
                                    catch (SqlException sqlEx)
                                    {
                                        throw new InvalidOperationException($"Database error inserting ItemVariantAttributes: {sqlEx.Message}", sqlEx);
                                    }
                                    catch (Exception ex)
                                    {
                                        throw new InvalidOperationException($"Failed to insert ItemVariantAttributes: {ex.Message}", ex);
                                    }
                                }
                            }
                        }
                        catch (SqlException sqlEx)
                        {
                            throw new InvalidOperationException($"Database error inserting ItemVariant: {sqlEx.Message}", sqlEx);
                        }
                        catch (Exception ex)
                        {
                            throw new InvalidOperationException($"Failed to insert ItemVariant: {ex.Message}", ex);
                        }
                    }

                    // Commit transaction - all operations succeeded
                    await transaction.CommitAsync();

                    // Set the collections on the item for the response
                    item.ItemAttributes = itemAttributes;
                    item.Variants = itemVariants;
                    
                    // Set ItemVariantAttributes on each variant
                    foreach (var variant in itemVariants)
                    {
                        variant.ItemVariantAttributes = itemVariantAttributes
                            .Where(va => va.ItemVariantID == variant.Id)
                            .ToList();
                    }

                    var response = new CreateItemResponse
                    {
                        Id = item.Id,
                        SellerID = item.SellerID,
                        Name_en = item.Name_en,
                        Name_fr = item.Name_fr,
                        Description_en = item.Description_en,
                        Description_fr = item.Description_fr,
                        ImageUrl = item.ImageUrl,
                        CategoryID = item.CategoryID,
                        Variants = MapToItemVariantDtos(item.Variants),
                        ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                        CreatedAt = item.CreatedAt,
                        UpdatedAt = item.UpdatedAt,
                        Deleted = item.Deleted
                    };

                    return Result.Success(response);
                }
                catch (InvalidOperationException)
                {
                    // Rollback transaction on error
                    await transaction.RollbackAsync();
                    throw; // Preserve the specific exception with context
                }
                catch (Exception ex)
                {
                    // Rollback transaction on error
                    await transaction.RollbackAsync();
                    throw new InvalidOperationException($"Transaction failed: {ex.Message}", ex);
                }
            }
            catch (Exception ex)
            {
                return Result.Failure<CreateItemResponse>($"An error occurred while creating the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetAllItemsAsync()
        {
            try
            {
                var items = await _itemRepository.GetAllAsync();
                var response = items.Select(item => MapItemToGetItemResponse(item));

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving items: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<GetItemResponse>> GetItemByIdAsync(Guid id)
        {
            try
            {
                var item = await _itemRepository.GetItemByIdAsync(id);
                if (item == null)
                {
                    return Result.Failure<GetItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                var response = MapItemToGetItemResponse(item);
                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<GetItemResponse>($"An error occurred while retrieving the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<GetItemResponse>> GetItemByIdIncludingDeletedAsync(Guid id)
        {
            try
            {
                // Use GetByIdAsync to retrieve items including soft-deleted ones for undelete operations
                // This differs from GetItemByIdAsync which excludes deleted items
                // Note: GetByIdAsync throws InvalidOperationException if item is not found (never returns null)
                var item = await _itemRepository.GetByIdAsync(id);
                var response = MapItemToGetItemResponse(item);
                return Result.Success(response);
            }
            catch (InvalidOperationException)
            {
                // GetByIdAsync throws InvalidOperationException when item is not found
                return Result.Failure<GetItemResponse>("Item not found.", StatusCodes.Status404NotFound);
            }
            catch (Exception ex)
            {
                return Result.Failure<GetItemResponse>($"An error occurred while retrieving the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        /// <summary>
        /// Maps an Item entity to a GetItemResponse DTO to eliminate code duplication.
        /// </summary>
        /// <param name="item">The Item entity to map.</param>
        /// <returns>A GetItemResponse DTO populated with data from the Item entity.</returns>
        private GetItemResponse MapItemToGetItemResponse(Item item)
        {
            return new GetItemResponse
            {
                Id = item.Id,
                SellerID = item.SellerID,
                Name_en = item.Name_en,
                Name_fr = item.Name_fr,
                Description_en = item.Description_en,
                Description_fr = item.Description_fr,
                ImageUrl = item.ImageUrl,
                CategoryID = item.CategoryID,
                Variants = MapToItemVariantDtos(item.Variants),
                ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                CreatedAt = item.CreatedAt,
                UpdatedAt = item.UpdatedAt,
                Deleted = item.Deleted
            };
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetAllItemsFromSellerAsync(Guid sellerId, bool includeDeleted = false)
        {
            try
            {
                var items = await _itemRepository.GetBySellerIdAsync(sellerId, includeDeleted);
                var response = items.Select(item => MapItemToGetItemResponse(item));

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving items for the seller: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<UpdateItemResponse>> UpdateItemAsync(UpdateItemRequest updateItemRequest)
        {
            try
            {
                var validationResult = updateItemRequest.Validate();
                if (validationResult.IsFailure)
                {
                    return Result.Failure<UpdateItemResponse>(validationResult.Error!, validationResult.ErrorCode ?? 400);
                }

                var existingItem = await _itemRepository.GetItemByIdAsync(updateItemRequest.Id);
                if (existingItem == null)
                {
                    return Result.Failure<UpdateItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                existingItem.SellerID = updateItemRequest.SellerID;
                existingItem.Name_en = updateItemRequest.Name_en;
                existingItem.Name_fr = updateItemRequest.Name_fr;
                existingItem.Description_en = updateItemRequest.Description_en;
                existingItem.Description_fr = updateItemRequest.Description_fr;
                existingItem.CategoryID = updateItemRequest.CategoryID;
                existingItem.Variants = updateItemRequest.Variants;
                existingItem.ItemAttributes = updateItemRequest.ItemAttributes;
                existingItem.UpdatedAt = DateTime.UtcNow;

                var updatedItem = await _itemRepository.UpdateAsync(existingItem);

                var response = new UpdateItemResponse
                {
                    Id = updatedItem.Id,
                    SellerID = updatedItem.SellerID,
                    Name_en = updatedItem.Name_en,
                    Name_fr = updatedItem.Name_fr,
                    Description_en = updatedItem.Description_en,
                    Description_fr = updatedItem.Description_fr,
                    ImageUrl = updatedItem.ImageUrl,
                    CategoryID = updatedItem.CategoryID,
                    Variants = MapToItemVariantDtos(updatedItem.Variants),
                    ItemAttributes = MapToItemAttributeDtos(updatedItem.ItemAttributes),
                    CreatedAt = updatedItem.CreatedAt,
                    UpdatedAt = updatedItem.UpdatedAt,
                    Deleted = updatedItem.Deleted
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<UpdateItemResponse>($"An error occurred while updating the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemResponse>> DeleteItemAsync(Guid id)
        {
            try
            {
                var item = await _itemRepository.GetItemByIdAsync(id);
                if (item == null)
                {
                    return Result.Failure<DeleteItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                await _itemRepository.DeleteAsync(item);

                var response = new DeleteItemResponse
                {
                    Id = id,
                    Message = "Item deleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemResponse>($"An error occurred while deleting the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemVariantResponse>> DeleteItemVariantAsync(Guid itemId, Guid variantId)
        {
            try
            {
                var success = await _itemVariantRepository.DeleteItemVariantAsync(itemId, variantId);
                if (!success)
                {
                    return Result.Failure<DeleteItemVariantResponse>("Item or variant not found.", StatusCodes.Status404NotFound);
                }

                var response = new DeleteItemVariantResponse
                {
                    ItemId = itemId,
                    VariantId = variantId,
                    Message = "Item variant deleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemVariantResponse>($"An error occurred while deleting the item variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemResponse>> UnDeleteItemAsync(Guid id)
        {
            try
            {
                // Use GetByIdAsync (not GetItemByIdAsync) to retrieve deleted items
                // GetItemByIdAsync filters out deleted items, but we need to find them to restore them
                var item = await _itemRepository.GetByIdAsync(id);
                if (item == null)
                {
                    return Result.Failure<DeleteItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                // Check if item is actually deleted before attempting to undelete
                if (!item.Deleted)
                {
                    return Result.Failure<DeleteItemResponse>("Item is not deleted.", StatusCodes.Status400BadRequest);
                }

                // Set Deleted to false to undelete the item
                item.Deleted = false;
                item.UpdatedAt = DateTime.UtcNow;
                await _itemRepository.UpdateAsync(item);

                var response = new DeleteItemResponse
                {
                    Id = id,
                    Message = "Item undeleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemResponse>($"An error occurred while undeleting the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemVariantResponse>> UnDeleteItemVariantAsync(Guid itemId, Guid variantId)
        {
            try
            {
                // Use GetByIdAsync to retrieve variant regardless of deleted status
                var variant = await _itemVariantRepository.GetByIdAsync(variantId);
                if (variant == null || variant.ItemId != itemId)
                {
                    return Result.Failure<DeleteItemVariantResponse>("Item or variant not found.", StatusCodes.Status404NotFound);
                }

                // Check if variant is actually deleted before attempting to undelete
                if (!variant.Deleted)
                {
                    return Result.Failure<DeleteItemVariantResponse>("Variant is not deleted.", StatusCodes.Status400BadRequest);
                }

                // Set Deleted to false to undelete the variant
                variant.Deleted = false;
                await _itemVariantRepository.UpdateAsync(variant);

                // Update the item's UpdatedAt timestamp
                var item = await _itemRepository.GetByIdAsync(itemId);
                if (item != null)
                {
                    item.UpdatedAt = DateTime.UtcNow;
                    await _itemRepository.UpdateAsync(item);
                }

                var response = new DeleteItemVariantResponse
                {
                    ItemId = itemId,
                    VariantId = variantId,
                    Message = "Item variant undeleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemVariantResponse>($"An error occurred while undeleting the item variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<GetItemResponse>> GetItemByVariantIdAsync(Guid variantId, Guid userId)
        {
            try
            {
                // Get seller's items and find the one containing the variant
                // This is more efficient than GetAllAsync as it's filtered by sellerId in the database
                var sellerItems = await _itemRepository.GetBySellerIdAsync(userId);
                var item = sellerItems.FirstOrDefault(i => 
                    !i.Deleted &&
                    i.Variants != null && 
                    i.Variants.Any(v => v.Id == variantId && !v.Deleted));

                if (item == null)
                {
                    return Result.Failure<GetItemResponse>("Variant not found or you do not have permission to access this item.", StatusCodes.Status404NotFound);
                }

                var response = MapItemToGetItemResponse(item);

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<GetItemResponse>($"An error occurred while retrieving item by variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result> UpdateItemVariantAsync(ItemVariant variant)
        {
            try
            {
                if (variant == null || variant.Id == Guid.Empty)
                {
                    return Result.Failure("Invalid variant data.", StatusCodes.Status400BadRequest);
                }

                // Update the variant - repository will handle if variant doesn't exist
                await _itemVariantRepository.UpdateAsync(variant);

                return Result.Success();
            }
            catch (Exception ex)
            {
                return Result.Failure($"An error occurred while updating the variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result> UpdateItemVariantImageAsync(Guid variantId, string imageType, string imageUrl, int imageNumber)
        {
            try
            {
                if (variantId == Guid.Empty)
                {
                    return Result.Failure("Invalid variant ID.", StatusCodes.Status400BadRequest);
                }

                if (string.IsNullOrWhiteSpace(imageUrl))
                {
                    return Result.Failure("Image URL is required.", StatusCodes.Status400BadRequest);
                }

                // NOTE: This method uses a read-modify-write pattern which could be subject to race conditions
                // if multiple concurrent requests update the same variant's images simultaneously.
                // Consider implementing one of the following approaches for production use:
                // 1. Optimistic concurrency control (add a RowVersion/Timestamp field to ItemVariant)
                // 2. Database-level locking mechanisms (e.g., SELECT FOR UPDATE)
                // 3. Application-level locking/semaphores for the same variant ID
                // For typical usage patterns (single user editing their own products), this is acceptable.

                // Get the variant from the repository
                var variant = await _itemVariantRepository.GetByIdAsync(variantId);
                if (variant == null)
                {
                    return Result.Failure("Variant not found.", StatusCodes.Status404NotFound);
                }

                // Update the appropriate field based on imageType
                if (imageType == "thumbnail")
                {
                    variant.ThumbnailUrl = imageUrl;
                }
                else if (imageType == "image")
                {
                    // ImageUrls is stored as comma-separated string
                    // Parse existing URLs, preserving empty slots
                    var existingUrls = string.IsNullOrEmpty(variant.ImageUrls)
                        ? new List<string>()
                        : variant.ImageUrls.Split(',').ToList();

                    // Add or replace the image URL at the specified position (imageNumber - 1)
                    var index = imageNumber - 1;
                    if (index < 0)
                    {
                        return Result.Failure("Image number must be greater than 0.", StatusCodes.Status400BadRequest);
                    }

                    // Ensure the list is large enough
                    while (existingUrls.Count <= index)
                    {
                        existingUrls.Add(string.Empty);
                    }

                    // Set the image URL at the correct position
                    existingUrls[index] = imageUrl;

                    // Join back to comma-separated string, keeping all positions (including empty)
                    variant.ImageUrls = string.Join(",", existingUrls);
                }
                else
                {
                    return Result.Failure("Invalid image type. Must be 'thumbnail' or 'image'.", StatusCodes.Status400BadRequest);
                }

                // Save the updated variant
                await _itemVariantRepository.UpdateAsync(variant);

                return Result.Success();
            }
            catch (Exception ex)
            {
                return Result.Failure($"An error occurred while updating the variant image: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        // Helper methods for mapping entities to DTOs
        private static ItemVariantAttributeDto MapToItemVariantAttributeDto(ItemVariantAttribute attribute)
        {
            return new ItemVariantAttributeDto
            {
                Id = attribute.Id,
                AttributeName_en = attribute.AttributeName_en,
                AttributeName_fr = attribute.AttributeName_fr,
                Attributes_en = attribute.Attributes_en,
                Attributes_fr = attribute.Attributes_fr
            };
        }

        private static ItemVariantDto MapToItemVariantDto(ItemVariant variant)
        {
            return new ItemVariantDto
            {
                Id = variant.Id,
                Price = variant.Price,
                StockQuantity = variant.StockQuantity,
                Sku = variant.Sku,
                ProductIdentifierType = variant.ProductIdentifierType,
                ProductIdentifierValue = variant.ProductIdentifierValue,
                ImageUrls = variant.ImageUrls,
                ThumbnailUrl = variant.ThumbnailUrl,
                ItemVariantName_en = variant.ItemVariantName_en,
                ItemVariantName_fr = variant.ItemVariantName_fr,
                ItemVariantAttributes = variant.ItemVariantAttributes?.Select(MapToItemVariantAttributeDto).ToList() ?? [],
                Deleted = variant.Deleted,
                Offer = variant.Offer,
                OfferStart = variant.OfferStart,
                OfferEnd = variant.OfferEnd
            };
        }

        private static ItemAttributeDto MapToItemAttributeDto(ItemAttribute attribute)
        {
            return new ItemAttributeDto
            {
                Id = attribute.Id,
                AttributeName_en = attribute.AttributeName_en,
                AttributeName_fr = attribute.AttributeName_fr,
                Attributes_en = attribute.Attributes_en,
                Attributes_fr = attribute.Attributes_fr
            };
        }

        private static List<ItemVariantDto> MapToItemVariantDtos(List<ItemVariant>? variants)
        {
            if (variants == null || variants.Count == 0)
            {
                return [];
            }
            return variants.Select(MapToItemVariantDto).ToList();
        }

        private static List<ItemAttributeDto> MapToItemAttributeDtos(List<ItemAttribute>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
            {
                return [];
            }
            return attributes.Select(MapToItemAttributeDto).ToList();
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetRecentlyAddedProductsAsync(int count = 100)
        {
            try
            {
                var items = await _itemRepository.GetRecentlyAddedProductsAsync(count);
                var response = items.Select(item => MapItemToGetItemResponse(item));

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving recently added products: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetSuggestedProductsAsync(int count = 4)
        {
            try
            {
                var items = await _itemRepository.GetSuggestedProductsAsync(count);
                var response = items.Select(item => MapItemToGetItemResponse(item));

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving suggested products: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetProductsWithOffersAsync(int count = 10)
        {
            try
            {
                // Query to get items with variants that have offers
                // Sort by best offer (highest percentage) first
                var items = await _itemRepository.GetProductsWithOffersAsync(count);
                var response = items.Select(item => MapItemToGetItemResponse(item));

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving products with offers: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result> UpdateItemVariantOfferAsync(UpdateItemVariantOfferRequest request)
        {
            try
            {
                // Validate the request
                // If there is an offer, both start and end dates must be provided
                // If there is no offer, all three fields (Offer, OfferStart, OfferEnd) must be null
                
                // Validate offer percentage range
                if (request.Offer.HasValue && (request.Offer < 0 || request.Offer > 100))
                {
                    return Result.Failure("Offer must be between 0 and 100", StatusCodes.Status400BadRequest);
                }

                if (request.Offer.HasValue)
                {
                    // If there's an offer, both dates are required
                    if (!request.OfferStart.HasValue || !request.OfferEnd.HasValue)
                    {
                        return Result.Failure("Both OfferStart and OfferEnd are required when setting an offer", StatusCodes.Status400BadRequest);
                    }

                    // Validate date range
                    if (request.OfferEnd < request.OfferStart)
                    {
                        return Result.Failure("OfferEnd must not be before OfferStart", StatusCodes.Status400BadRequest);
                    }
                }
                else
                {
                    // If there's no offer, dates should also be null
                    if (request.OfferStart.HasValue || request.OfferEnd.HasValue)
                    {
                        return Result.Failure("OfferStart and OfferEnd must be null when there is no offer", StatusCodes.Status400BadRequest);
                    }
                }

                // Get the variant
                var variant = await _itemVariantRepository.GetByIdAsync(request.VariantId);
                if (variant == null)
                {
                    return Result.Failure("Variant not found", StatusCodes.Status404NotFound);
                }

                // Update the offer fields
                variant.Offer = request.Offer;
                variant.OfferStart = request.OfferStart;
                variant.OfferEnd = request.OfferEnd;

                // Save changes
                await _itemVariantRepository.UpdateAsync(variant);

                return Result.Success();
            }
            catch (Exception ex)
            {
                return Result.Failure($"An error occurred while updating variant offer: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }
    }
}