using System.Data;
using Dapper;
using Domain.Models.Requests;
using Domain.Models.Responses;
using Domain.Services.Interfaces;
using Helpers.Common;
using Infrastructure.Data;
using Infrastructure.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;

namespace Domain.Services.Implementations
{
    public class ItemService(
        IItemRepository itemRepository, 
        IItemVariantRepository itemVariantRepository,
        IItemAttributeRepository itemAttributeRepository,
        IItemVariantAttributeRepository itemVariantAttributeRepository,
        string connectionString) : IItemService
    {
        private readonly IItemRepository _itemRepository = itemRepository;
        private readonly IItemVariantRepository _itemVariantRepository = itemVariantRepository;
        private readonly IItemAttributeRepository _itemAttributeRepository = itemAttributeRepository;
        private readonly IItemVariantAttributeRepository _itemVariantAttributeRepository = itemVariantAttributeRepository;
        private readonly string _connectionString = connectionString;

        public async Task<Result<CreateItemResponse>> CreateItemAsync(CreateItemRequest createItemRequest)
        {
            try
            {
                var validationResult = createItemRequest.Validate();
                if (validationResult.IsFailure)
                {
                    return Result.Failure<CreateItemResponse>(validationResult.Error!, validationResult.ErrorCode ?? 400);
                }

                var createdAt = DateTime.UtcNow;

                // Prepare Item (Id will be generated by database)
                var item = new Item
                {
                    SellerID = createItemRequest.SellerID,
                    Name_en = createItemRequest.Name_en,
                    Name_fr = createItemRequest.Name_fr,
                    Description_en = createItemRequest.Description_en,
                    Description_fr = createItemRequest.Description_fr,
                    CategoryID = createItemRequest.CategoryID,
                    CreatedAt = createdAt,
                    UpdatedAt = null,
                    Deleted = false
                };

                // Prepare ItemAttributes (Id and ItemID will be set after Item is inserted)
                var itemAttributeRequests = createItemRequest.ItemAttributes.ToList();

                // Prepare ItemVariants and ItemVariantAttributes (Ids will be set after insertion)
                var itemVariantRequests = createItemRequest.Variants.ToList();

                // Execute all database operations in a single transaction
                using var connection = new SqlConnection(_connectionString);
                await connection.OpenAsync();
                using var transaction = connection.BeginTransaction();

                try
                {
                    // 1. Insert Item and get database-generated Id
                    try
                    {
                        var itemQuery = @"
INSERT INTO dbo.Item (
    SellerID,
    Name_en, 
    Name_fr, 
    Description_en, 
    Description_fr, 
    CategoryID, 
    CreatedAt, 
    UpdatedAt, 
    Deleted)
OUTPUT INSERTED.Id
VALUES (
    @SellerID,
    @Name_en, 
    @Name_fr, 
    @Description_en, 
    @Description_fr, 
    @CategoryID, 
    @CreatedAt, 
    @UpdatedAt, 
    @Deleted)";

                        var itemId = await connection.ExecuteScalarAsync<Guid>(itemQuery, item, transaction);
                        item.Id = itemId;
                    }
                    catch (SqlException sqlEx)
                    {
                        throw new InvalidOperationException($"Database error inserting Item: {sqlEx.Message}", sqlEx);
                    }
                    catch (Exception ex)
                    {
                        throw new InvalidOperationException($"Failed to insert Item: {ex.Message}", ex);
                    }

                    // 2. Insert ItemAttributes
                    var itemAttributes = new List<ItemAttribute>();
                    if (itemAttributeRequests.Any())
                    {
                        try
                        {
                            var itemAttributeQuery = @"
INSERT INTO dbo.ItemAttribute (ItemID, AttributeName_en, AttributeName_fr, Attributes_en, Attributes_fr)
OUTPUT INSERTED.Id
VALUES (@ItemID, @AttributeName_en, @AttributeName_fr, @Attributes_en, @Attributes_fr)";

                            foreach (var attributeRequest in itemAttributeRequests)
                            {
                                var attributeId = await connection.ExecuteScalarAsync<Guid>(itemAttributeQuery, new
                                {
                                    ItemID = item.Id,
                                    attributeRequest.AttributeName_en,
                                    attributeRequest.AttributeName_fr,
                                    attributeRequest.Attributes_en,
                                    attributeRequest.Attributes_fr
                                }, transaction);

                                itemAttributes.Add(new ItemAttribute
                                {
                                    Id = attributeId,
                                    ItemID = item.Id,
                                    AttributeName_en = attributeRequest.AttributeName_en,
                                    AttributeName_fr = attributeRequest.AttributeName_fr,
                                    Attributes_en = attributeRequest.Attributes_en,
                                    Attributes_fr = attributeRequest.Attributes_fr
                                });
                            }
                        }
                        catch (SqlException sqlEx)
                        {
                            throw new InvalidOperationException($"Database error inserting ItemAttributes: {sqlEx.Message}", sqlEx);
                        }
                        catch (Exception ex)
                        {
                            throw new InvalidOperationException($"Failed to insert ItemAttributes: {ex.Message}", ex);
                        }
                    }

                    // 3. Insert ItemVariants
                    var itemVariants = new List<ItemVariant>();
                    var itemVariantAttributes = new List<ItemVariantAttribute>();
                    if (itemVariantRequests.Any())
                    {
                        try
                        {
                            var itemVariantQuery = @"
INSERT INTO dbo.ItemVariant (
    ItemId,
    Price,
    StockQuantity,
    Sku,
    ProductIdentifierType,
    ProductIdentifierValue,
    ImageUrls,
    ThumbnailUrl,
    ItemVariantName_en,
    ItemVariantName_fr,
    Deleted)
OUTPUT INSERTED.Id
VALUES (
    @ItemId,
    @Price,
    @StockQuantity,
    @Sku,
    @ProductIdentifierType,
    @ProductIdentifierValue,
    @ImageUrls,
    @ThumbnailUrl,
    @ItemVariantName_en,
    @ItemVariantName_fr,
    @Deleted)";

                            foreach (var variantRequest in itemVariantRequests)
                            {
                                var variantId = await connection.ExecuteScalarAsync<Guid>(itemVariantQuery, new
                                {
                                    ItemId = item.Id,
                                    variantRequest.Price,
                                    variantRequest.StockQuantity,
                                    variantRequest.Sku,
                                    variantRequest.ProductIdentifierType,
                                    variantRequest.ProductIdentifierValue,
                                    variantRequest.ImageUrls,
                                    variantRequest.ThumbnailUrl,
                                    variantRequest.ItemVariantName_en,
                                    variantRequest.ItemVariantName_fr,
                                    variantRequest.Deleted
                                }, transaction);

                                var variant = new ItemVariant
                                {
                                    Id = variantId,
                                    ItemId = item.Id,
                                    Price = variantRequest.Price,
                                    StockQuantity = variantRequest.StockQuantity,
                                    Sku = variantRequest.Sku,
                                    ProductIdentifierType = variantRequest.ProductIdentifierType,
                                    ProductIdentifierValue = variantRequest.ProductIdentifierValue,
                                    ImageUrls = variantRequest.ImageUrls,
                                    ThumbnailUrl = variantRequest.ThumbnailUrl,
                                    ItemVariantName_en = variantRequest.ItemVariantName_en,
                                    ItemVariantName_fr = variantRequest.ItemVariantName_fr,
                                    Deleted = variantRequest.Deleted
                                };
                                itemVariants.Add(variant);

                                // 4. Insert ItemVariantAttributes for this variant
                                if (variantRequest.ItemVariantAttributes.Any())
                                {
                                    try
                                    {
                                        var itemVariantAttributeQuery = @"
INSERT INTO dbo.ItemVariantAttribute (ItemVariantID, AttributeName_en, AttributeName_fr, Attributes_en, Attributes_fr)
OUTPUT INSERTED.Id
VALUES (@ItemVariantID, @AttributeName_en, @AttributeName_fr, @Attributes_en, @Attributes_fr)";

                                        foreach (var variantAttributeRequest in variantRequest.ItemVariantAttributes)
                                        {
                                            var variantAttributeId = await connection.ExecuteScalarAsync<Guid>(itemVariantAttributeQuery, new
                                            {
                                                ItemVariantID = variantId,
                                                variantAttributeRequest.AttributeName_en,
                                                variantAttributeRequest.AttributeName_fr,
                                                variantAttributeRequest.Attributes_en,
                                                variantAttributeRequest.Attributes_fr
                                            }, transaction);

                                            itemVariantAttributes.Add(new ItemVariantAttribute
                                            {
                                                Id = variantAttributeId,
                                                ItemVariantID = variantId,
                                                AttributeName_en = variantAttributeRequest.AttributeName_en,
                                                AttributeName_fr = variantAttributeRequest.AttributeName_fr,
                                                Attributes_en = variantAttributeRequest.Attributes_en,
                                                Attributes_fr = variantAttributeRequest.Attributes_fr
                                            });
                                        }
                                    }
                                    catch (SqlException sqlEx)
                                    {
                                        throw new InvalidOperationException($"Database error inserting ItemVariantAttributes: {sqlEx.Message}", sqlEx);
                                    }
                                    catch (Exception ex)
                                    {
                                        throw new InvalidOperationException($"Failed to insert ItemVariantAttributes: {ex.Message}", ex);
                                    }
                                }
                            }
                        }
                        catch (SqlException sqlEx)
                        {
                            throw new InvalidOperationException($"Database error inserting ItemVariant: {sqlEx.Message}", sqlEx);
                        }
                        catch (Exception ex)
                        {
                            throw new InvalidOperationException($"Failed to insert ItemVariant: {ex.Message}", ex);
                        }
                    }

                    // Commit transaction - all operations succeeded
                    await transaction.CommitAsync();

                    // Set the collections on the item for the response
                    item.ItemAttributes = itemAttributes;
                    item.Variants = itemVariants;
                    
                    // Set ItemVariantAttributes on each variant
                    foreach (var variant in itemVariants)
                    {
                        variant.ItemVariantAttributes = itemVariantAttributes
                            .Where(va => va.ItemVariantID == variant.Id)
                            .ToList();
                    }

                    var response = new CreateItemResponse
                    {
                        Id = item.Id,
                        SellerID = item.SellerID,
                        Name_en = item.Name_en,
                        Name_fr = item.Name_fr,
                        Description_en = item.Description_en,
                        Description_fr = item.Description_fr,
                        ImageUrl = item.ImageUrl,
                        CategoryID = item.CategoryID,
                        Variants = MapToItemVariantDtos(item.Variants),
                        ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                        CreatedAt = item.CreatedAt,
                        UpdatedAt = item.UpdatedAt,
                        Deleted = item.Deleted
                    };

                    return Result.Success(response);
                }
                catch (InvalidOperationException)
                {
                    // Rollback transaction on error
                    await transaction.RollbackAsync();
                    throw; // Preserve the specific exception with context
                }
                catch (Exception ex)
                {
                    // Rollback transaction on error
                    await transaction.RollbackAsync();
                    throw new InvalidOperationException($"Transaction failed: {ex.Message}", ex);
                }
            }
            catch (Exception ex)
            {
                return Result.Failure<CreateItemResponse>($"An error occurred while creating the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetAllItemsAsync()
        {
            try
            {
                var items = await _itemRepository.GetAllAsync();
                var response = items.Select(item => new GetItemResponse
                {
                    Id = item.Id,
                    SellerID = item.SellerID,
                    Name_en = item.Name_en,
                    Name_fr = item.Name_fr,
                    Description_en = item.Description_en,
                    Description_fr = item.Description_fr,
                    ImageUrl = item.ImageUrl,
                    CategoryID = item.CategoryID,
                    Variants = MapToItemVariantDtos(item.Variants),
                    ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                    CreatedAt = item.CreatedAt,
                    UpdatedAt = item.UpdatedAt,
                    Deleted = item.Deleted
                });

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving items: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<GetItemResponse>> GetItemByIdAsync(Guid id)
        {
            try
            {
                var item = await _itemRepository.GetItemByIdAsync(id);
                if (item == null)
                {
                    return Result.Failure<GetItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                var response = new GetItemResponse
                {
                    Id = item.Id,
                    SellerID = item.SellerID,
                    Name_en = item.Name_en,
                    Name_fr = item.Name_fr,
                    Description_en = item.Description_en,
                    Description_fr = item.Description_fr,
                    ImageUrl = item.ImageUrl,
                    CategoryID = item.CategoryID,
                    Variants = MapToItemVariantDtos(item.Variants),
                    ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                    CreatedAt = item.CreatedAt,
                    UpdatedAt = item.UpdatedAt,
                    Deleted = item.Deleted
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<GetItemResponse>($"An error occurred while retrieving the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<IEnumerable<GetItemResponse>>> GetAllItemsFromSellerAsync(Guid sellerId)
        {
            try
            {
                var items = await _itemRepository.GetBySellerIdAsync(sellerId);
                var response = items.Select(item => new GetItemResponse
                {
                    Id = item.Id,
                    SellerID = item.SellerID,
                    Name_en = item.Name_en,
                    Name_fr = item.Name_fr,
                    Description_en = item.Description_en,
                    Description_fr = item.Description_fr,
                    ImageUrl = item.ImageUrl,
                    CategoryID = item.CategoryID,
                    Variants = MapToItemVariantDtos(item.Variants),
                    ItemAttributes = MapToItemAttributeDtos(item.ItemAttributes),
                    CreatedAt = item.CreatedAt,
                    UpdatedAt = item.UpdatedAt,
                    Deleted = item.Deleted
                });

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<IEnumerable<GetItemResponse>>($"An error occurred while retrieving items for the seller: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<UpdateItemResponse>> UpdateItemAsync(UpdateItemRequest updateItemRequest)
        {
            try
            {
                var validationResult = updateItemRequest.Validate();
                if (validationResult.IsFailure)
                {
                    return Result.Failure<UpdateItemResponse>(validationResult.Error!, validationResult.ErrorCode ?? 400);
                }

                var existingItem = await _itemRepository.GetItemByIdAsync(updateItemRequest.Id);
                if (existingItem == null)
                {
                    return Result.Failure<UpdateItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                existingItem.SellerID = updateItemRequest.SellerID;
                existingItem.Name_en = updateItemRequest.Name_en;
                existingItem.Name_fr = updateItemRequest.Name_fr;
                existingItem.Description_en = updateItemRequest.Description_en;
                existingItem.Description_fr = updateItemRequest.Description_fr;
                existingItem.CategoryID = updateItemRequest.CategoryID;
                existingItem.Variants = updateItemRequest.Variants;
                existingItem.ItemAttributes = updateItemRequest.ItemAttributes;
                existingItem.UpdatedAt = DateTime.UtcNow;

                var updatedItem = await _itemRepository.UpdateAsync(existingItem);

                var response = new UpdateItemResponse
                {
                    Id = updatedItem.Id,
                    SellerID = updatedItem.SellerID,
                    Name_en = updatedItem.Name_en,
                    Name_fr = updatedItem.Name_fr,
                    Description_en = updatedItem.Description_en,
                    Description_fr = updatedItem.Description_fr,
                    ImageUrl = updatedItem.ImageUrl,
                    CategoryID = updatedItem.CategoryID,
                    Variants = MapToItemVariantDtos(updatedItem.Variants),
                    ItemAttributes = MapToItemAttributeDtos(updatedItem.ItemAttributes),
                    CreatedAt = updatedItem.CreatedAt,
                    UpdatedAt = updatedItem.UpdatedAt,
                    Deleted = updatedItem.Deleted
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<UpdateItemResponse>($"An error occurred while updating the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemResponse>> DeleteItemAsync(Guid id)
        {
            try
            {
                var item = await _itemRepository.GetItemByIdAsync(id);
                if (item == null)
                {
                    return Result.Failure<DeleteItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                await _itemRepository.DeleteAsync(item);

                var response = new DeleteItemResponse
                {
                    Id = id,
                    Message = "Item deleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemResponse>($"An error occurred while deleting the item: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<DeleteItemVariantResponse>> DeleteItemVariantAsync(Guid itemId, Guid variantId)
        {
            try
            {
                var success = await _itemVariantRepository.DeleteItemVariantAsync(itemId, variantId);
                if (!success)
                {
                    return Result.Failure<DeleteItemVariantResponse>("Item or variant not found.", StatusCodes.Status404NotFound);
                }

                var response = new DeleteItemVariantResponse
                {
                    ItemId = itemId,
                    VariantId = variantId,
                    Message = "Item variant deleted successfully.",
                    Success = true
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<DeleteItemVariantResponse>($"An error occurred while deleting the item variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        public async Task<Result<GetItemResponse>> GetItemByVariantIdAsync(Guid variantId, Guid userId)
        {
            try
            {
                // Query to find the item that contains the specified variant and belongs to the user
                using var connection = new SqlConnection(_connectionString);
                await connection.OpenAsync();

                var query = @"
                    SELECT i.*
                    FROM dbo.Item i
                    INNER JOIN dbo.ItemVariant iv ON i.Id = iv.ItemId
                    WHERE iv.Id = @VariantId 
                    AND i.SellerID = @UserId
                    AND i.Deleted = 0
                    AND iv.Deleted = 0";

                var item = await connection.QueryFirstOrDefaultAsync<Item>(query, new { VariantId = variantId, UserId = userId });

                if (item == null)
                {
                    return Result.Failure<GetItemResponse>("Variant not found or you do not have permission to access this item.", StatusCodes.Status404NotFound);
                }

                // Get full item details with variants and attributes
                var fullItem = await _itemRepository.GetItemByIdAsync(item.Id);
                if (fullItem == null)
                {
                    return Result.Failure<GetItemResponse>("Item not found.", StatusCodes.Status404NotFound);
                }

                var response = new GetItemResponse
                {
                    Id = fullItem.Id,
                    SellerID = fullItem.SellerID,
                    Name_en = fullItem.Name_en,
                    Name_fr = fullItem.Name_fr,
                    Description_en = fullItem.Description_en,
                    Description_fr = fullItem.Description_fr,
                    ImageUrl = fullItem.ImageUrl,
                    CategoryID = fullItem.CategoryID,
                    Variants = MapToItemVariantDtos(fullItem.Variants),
                    ItemAttributes = MapToItemAttributeDtos(fullItem.ItemAttributes),
                    CreatedAt = fullItem.CreatedAt,
                    UpdatedAt = fullItem.UpdatedAt,
                    Deleted = fullItem.Deleted
                };

                return Result.Success(response);
            }
            catch (Exception ex)
            {
                return Result.Failure<GetItemResponse>($"An error occurred while retrieving item by variant: {ex.Message}", StatusCodes.Status500InternalServerError);
            }
        }

        // Helper methods for mapping entities to DTOs
        private static ItemVariantAttributeDto MapToItemVariantAttributeDto(ItemVariantAttribute attribute)
        {
            return new ItemVariantAttributeDto
            {
                Id = attribute.Id,
                AttributeName_en = attribute.AttributeName_en,
                AttributeName_fr = attribute.AttributeName_fr,
                Attributes_en = attribute.Attributes_en,
                Attributes_fr = attribute.Attributes_fr
            };
        }

        private static ItemVariantDto MapToItemVariantDto(ItemVariant variant)
        {
            return new ItemVariantDto
            {
                Id = variant.Id,
                Price = variant.Price,
                StockQuantity = variant.StockQuantity,
                Sku = variant.Sku,
                ProductIdentifierType = variant.ProductIdentifierType,
                ProductIdentifierValue = variant.ProductIdentifierValue,
                ImageUrls = variant.ImageUrls,
                ThumbnailUrl = variant.ThumbnailUrl,
                ItemVariantName_en = variant.ItemVariantName_en,
                ItemVariantName_fr = variant.ItemVariantName_fr,
                ItemVariantAttributes = variant.ItemVariantAttributes?.Select(MapToItemVariantAttributeDto).ToList() ?? [],
                Deleted = variant.Deleted
            };
        }

        private static ItemAttributeDto MapToItemAttributeDto(ItemAttribute attribute)
        {
            return new ItemAttributeDto
            {
                Id = attribute.Id,
                AttributeName_en = attribute.AttributeName_en,
                AttributeName_fr = attribute.AttributeName_fr,
                Attributes_en = attribute.Attributes_en,
                Attributes_fr = attribute.Attributes_fr
            };
        }

        private static List<ItemVariantDto> MapToItemVariantDtos(List<ItemVariant>? variants)
        {
            if (variants == null || variants.Count == 0)
            {
                return [];
            }
            return variants.Select(MapToItemVariantDto).ToList();
        }

        private static List<ItemAttributeDto> MapToItemAttributeDtos(List<ItemAttribute>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
            {
                return [];
            }
            return attributes.Select(MapToItemAttributeDto).ToList();
        }
    }
}